import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  // Resolves the `@/*` alias from tsconfig.json so tests import the same way app
  // code does. Native since Vite 7 — the `vite-tsconfig-paths` plugin is no
  // longer needed and warns if installed.
  resolve: { tsconfigPaths: true },
  test: {
    coverage: {
      // Generated by the shadcn CLI — see the linter override in biome.jsonc.
      exclude: [
        "components/ui/**",
        "hooks/use-mobile.ts",
        "**/*.test.{ts,tsx}",
      ],
      include: [
        "app/**",
        "components/**",
        "hooks/**",
        "lib/**",
        "shared/**",
        "sidecar/**",
      ],
      provider: "v8",
      reporter: ["text", "lcov"],
    },
    environment: "jsdom",
    exclude: [
      "node_modules/**",
      // Vendored third-party checkouts have their own suites; never run them.
      "repos/**",
      ".next/**",
      "out/**",
      "src-tauri/**",
    ],
    globals: false,
    include: ["**/*.{test,spec}.{ts,tsx}"],
    // Sharing one module graph across files halves the run (17.6 s against
    // 34.5 s, measured at three workers) and breaks every suite that mocks a
    // module: `vi.mock` cannot reach a module an earlier file already
    // evaluated, so use-tours wrote to the real store and asset-source-card
    // called the real dialog. Isolation is the default; it is written down so
    // the number beside it is too.
    isolate: true,
    // Vitest's default is every core but one. On a fanless laptop that is
    // seven node processes at full tilt and a load average past thirty for the
    // length of a run; three leaves the machine usable while it runs.
    // `VITEST_MAX_WORKERS` still overrides it, which is what a CI runner would
    // set.
    maxWorkers: 3,
    setupFiles: ["./vitest.setup.ts"],
    // Has to sit above the `asyncUtilTimeout` in vitest.setup.ts, or a query
    // that will never resolve burns the whole test budget and dies here — with
    // "test timed out" instead of Testing Library's "unable to find element".
    testTimeout: 15_000,
  },
});
